import { StyleSheet, Platform } from 'react-native';
import { SIZES } from '../globalStyles';

export const createStyles = (cores: any) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: cores.background,
  },
  header: {
    backgroundColor: cores.acao,
    paddingTop: SIZES.padding,
    paddingBottom: SIZES.padding,
    paddingHorizontal: SIZES.padding,
    flexDirection: 'row',
    alignItems: 'center',
    gap: SIZES.radius,
  },
  backButton: {
    padding: 4,
  },
  logoHeaderWrapper: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: cores.white,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 4,
  },
  logoHeader: {
    width: 36,
    height: 36,
    resizeMode: 'contain',
  },
  headerTitle: {
    flex: 1,
    fontSize: SIZES.fontTitle,
    fontWeight: 'bold',
    color: cores.white,
  },
  card: {
    backgroundColor: cores.cardBackground,
    borderRadius: SIZES.radius,
    borderWidth: 0.5,
    borderColor: cores.border,
    padding: 14,
    marginHorizontal: SIZES.padding,
    marginBottom: 10,
    ...Platform.select({
      ios: {
        shadowColor: cores.black,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.06,
        shadowRadius: 4,
      },
      android: { elevation: 2 },
    }),
  },
  cardTitulo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 12,
  },
  cardTituloTexto: {
    fontSize: SIZES.fontCaption,
    fontWeight: 'bold',
    color: cores.primary,
  },
  temaOpcoes: {
    flexDirection: 'row',
    gap: 8,
  },
  temaOpcao: {
    flex: 1,
    paddingVertical: 8,
    borderRadius: SIZES.radiusSmall,
    alignItems: 'center',
    gap: 4,
    borderWidth: 0.5,
    borderColor: cores.border,
  },
  temaOpcaoAtiva: {
    backgroundColor: cores.acao,
    borderColor: cores.acao,
  },
  temaOpcaoTexto: {
    fontSize: SIZES.fontSmall,
    color: cores.textSecondary,
  },
  temaOpcaoTextoAtiva: {
    color: cores.verdeClaro,
    fontWeight: '500',
  },
  itemLinha: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 6,
    borderBottomWidth: 0.5,
    borderBottomColor: cores.border,
  },
  itemLinhaUltimo: {
    borderBottomWidth: 0,
    paddingBottom: 0,
  },
  itemLabel: {
    fontSize: SIZES.fontSmall,
    color: cores.textSecondary,
  },
  itemValor: {
    fontSize: SIZES.fontSmall,
    fontWeight: '500',
    color: cores.primary,
  },
  privacidadeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  privacidadeTitulo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  logoutCard: {
    backgroundColor: cores.cardBackground,
    borderRadius: SIZES.radius,
    borderWidth: 0.5,
    borderColor: cores.error,
    padding: 14,
    marginHorizontal: SIZES.padding,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  logoutTexto: {
    fontSize: SIZES.fontCaption,
    fontWeight: 'bold',
    color: cores.error,
  },
  limiteItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 0.5,
    borderBottomColor: cores.border,
  },
  limiteItemUltimo: {
    borderBottomWidth: 0,
  },
  limiteLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flex: 1,
  },
  limiteLabel: {
    fontSize: SIZES.fontSmall,
    color: cores.textPrimary,
    flex: 1,
  },
  limiteInput: {
    width: 64,
    borderWidth: 0.5,
    borderColor: cores.border,
    borderRadius: SIZES.radiusSmall,
    padding: 6,
    fontSize: SIZES.fontCaption,
    color: cores.textPrimary,
    textAlign: 'center',
    backgroundColor: cores.background,
  },
  limiteErro: {
    fontSize: SIZES.fontSmall,
    color: cores.error,
    marginTop: 8,
    textAlign: 'center',
  },
  salvarLimitesButton: {
    backgroundColor: cores.acao,
    borderRadius: SIZES.radiusLarge,
    paddingVertical: 10,
    alignItems: 'center',
    marginTop: 12,
  },
  salvarLimitesTexto: {
    fontSize: SIZES.fontCaption,
    fontWeight: 'bold',
    color: cores.white,
  },
  excluirCard: {
    backgroundColor: cores.cardBackground,
    borderRadius: SIZES.radius,
    borderWidth: 0.5,
    borderColor: cores.error,
    padding: 14,
    marginHorizontal: SIZES.padding,
    marginBottom: SIZES.padding,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  excluirTexto: {
    fontSize: SIZES.fontCaption,
    fontWeight: 'bold',
    color: cores.error,
  },
  excluirDescricao: {
    fontSize: SIZES.fontSmall,
    color: cores.error,
    opacity: 0.7,
    marginTop: 2,
  },
});